export const FETCH_MOVIES_LIST = 'FETCH_MOVIES_LIST'
export const FETCH_MOVIES_LIST_SUCCESS = 'FETCH_MOVIES_LIST_SUCCESS'
export const FETCH_MOVIES_LIST_ERROR = 'FETCH_MOVIES_LIST_ERROR'

export const FETCH_MOVIE = 'FETCH_MOVIE'
export const FETCH_MOVIE_SUCCESS = 'FETCH_MOVIE_SUCCESS'
export const FETCH_MOVIE_ERROR = 'FETCH_MOVIE_ERROR'
